import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "Next.js Tutorial",
    template: "%s | Trial",
  },
  description: "Generated by nextjs",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="header flex items-center justify-between px-6 py-3">
          {/* Left side brand name */}
          <p className="brandName text-2xl font-extrabold tracking-wide">
            Book Store
          </p>

          {/* Right side icons */}
          <div className="flex items-center space-x-8">
            <Link href="/cart">
              <Image
                src="/icons/shopping-cart.png"
                alt="Cart"
                width={28}
                height={28}
                className="cursor-pointer"
              />
            </Link>
            <Link href="/user">
              <Image
                src="/icons/user.png"
                alt="User"
                width={28}
                height={28}
                className="cursor-pointer"
              />
            </Link>
            <Link href="/offers">
              <Image
                src="/icons/percent.png"
                alt="Discounts"
                width={28}
                height={28}
                className="cursor-pointer"
              />
            </Link>
          </div>
        </header>

        <main>{children}</main>

      </body>
    </html>
  );
}
